# Generated by Django 2.2.8 on 2020-01-02 11:11

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_projo_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projo_post',
            name='landing_page',
        ),
        migrations.RemoveField(
            model_name='projo_post',
            name='repo_name',
        ),
        migrations.AddField(
            model_name='projo_post',
            name='landing_page_pic',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
